### PR TITLE
add msql folder and bash script

### PR DESCRIPTION
**Pull request by CarolineMorton**

### CODE REVIEW

**Comment by wjchulme** [comment]
No longer getting "can't find install_mssql.sh" error when running `py run.py`, but still not working:

capture

**Comment by CarolineMorton** [comment]
Interesting - it works for me on a mac. I can run `python run.py` without complaint as well as running the alternative `jupyter notebook`. When I run the former,  it goes through all the steps - 13 in total - takes a while but it does complete them, and launches juptyerlab window in the browser. This seems to work as normal and expected. 

Not sure why it doesn't work for you. Main differences could be that I am: 
- Using a virtual environment. 
- Using Python 3.8
- Being on a mac. 

@sebbacon what do you think is going on here?

**Comment by CarolineMorton** [comment]
It seems that this issue is related to line 1 of `install_mysql.sh` which is `set -e -o pipefail`. On windows, this appears to cause issues due to its _seeing_ the end of the line as earlier than the actual end of the line. See https://askubuntu.com/questions/1044280/set-eo-pipefail-not-working-in-windows-subsystem-for-linux-ubuntu-16-04

**Comment by CarolineMorton** [comment]
@wjchulme did you get this working? and if so, can we merge?

**Review by wjchulme — APPROVED** [review]

**Comment by wjchulme** [comment]
@CarolineMorton works!

**Comment by sebbacon** [comment]
Just to note that although this works the correct fix is actually to *remove* all reference to mysql.

In fact the *really* correct fix is to get rid of `run.py` completely, per https://github.com/opensafely-core/opensafely-cli/issues/29, but yknow, time...

**Pull request merged**
